<?php 
$access = $this->access;

$title = $this->translate('New SOAP-account');
$this->headTitle($title);

$form = $this->makeFormHorizontal($form);
$this->form($form, \TwbBundle\Form\View\Helper\TwbBundleForm::LAYOUT_HORIZONTAL);

$menuContainer = $this->navigation('navigation')->getContainer();

$menuContainer->findOneBy('route', 'user/createSoapUser')->setActive();


?>

<?php $this->placeholder('sidebar_left')->captureStart() ?>
<?php $this->placeholder('sidebar_left')->captureEnd() ?>

<?php $this->placeholder('sidebar_right')->captureStart() ?>
<?php $this->placeholder('sidebar_right')->captureEnd() ?>



<div class="form">
<h1><?php echo $title ?></h1>

<?php
$form = $this->form;
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formcollection($form);
echo $this->form()->closeTag($form);

?>

</div>
