<?php 
$access = $this->access;

$title = $this->translate('New SOAP-account');
$this->headTitle($title);

$this->getHelperPluginManager()->setAlias('formRow', \Iaasen\View\Helper\FormRowHorizontal::class);
$this->formCollection()->setDefaultElementHelper('formRowHorizontal');
$form = $this->form;
$form->setAttribute('class', 'form-horizontal');
$form->prepare();

$menuContainer = $this->navigation('navigation')->getContainer();
$menuContainer->findOneBy('route', 'user/createSoapUser')->setActive();

?>

<?php $this->placeholder('sidebar_left')->captureStart() ?>
<?php $this->placeholder('sidebar_left')->captureEnd() ?>

<?php $this->placeholder('sidebar_right')->captureStart() ?>
<?php $this->placeholder('sidebar_right')->captureEnd() ?>



<div class="form">
<h1><?= $title ?></h1>

<?php
    echo $this->form()->openTag($form);
    echo $this->formCollection($form);
    echo $this->form()->closeTag($form);
?>

</div>
