<?php
/**
 * User: iaase
 * Date: 03.12.2017
 * Time: 22.06
 * @var Acl\Model\Group[] $groups
 * @var Acl\Model\User $user
 */

?>

<h1>Ny bruker</h1>

<p>
	Hei <?= $user->name ?>.<br>
	Vi ser du har logget inn med konto fra Elfag intranett (brukernavn <?= $user->username ?>).<br>
	Ifølge intranett heter firmaet ditt: <b><?= $user->ludens_company->name ?></b><br>
	Vi kan ikke se at noen fra det firmaet har logget inn her før.<br>
</p>


<form method="post">
	<div class="form-group">
		<div class="radio">
			<label>
				<input type="radio" name="company" value="new">
				Det er som ventet, dette er første gang jeg logger inn her.
			</label>
		</div>
		<?php foreach($groups AS $group): ?>
			<div class="radio">
				<label>
					<input type="radio" name="company" value="<?= $group->id ?>">
					<?= $group->name ?>
				</label>
			</div>
		<?php endforeach; ?>
		<div class="radio">
			<label>
				<input type="radio" name="company" value="missing">
				Jeg har brukt tjenesten før og burde se firmaet mitt her. Vær vennlig å sjekk dette for meg.
			</label>
		</div>
		<input type="submit" value="Lagre">
	</div>
</form>
