<?php
$form = $this->form;


$title = $this->translate('User');
$this->headTitle($title);

$form = $this->makeFormHorizontal($form);
$this->form($form, \TwbBundle\Form\View\Helper\TwbBundleForm::LAYOUT_HORIZONTAL);

$menuContainer = $this->navigation('navigation')->getContainer();
$menuContainer->findOneBy('route', 'user/editaccess')->setActive();

?>


<?php $this->placeholder('sidebar_left')->captureStart() ?>
<?php $this->placeholder('sidebar_left')->captureEnd() ?>

<?php $this->placeholder('sidebar_right')->captureStart() ?>
<?php $this->placeholder('sidebar_right')->captureEnd() ?>



<h1><?=$this->escapeHtml($title)?></h1>

<div class="form">
	<?php
	echo $this->form()->openTag($form);
	echo $this->formCollection($form);
// 	echo $this->formRow($form->get('username'));
// 	echo $this->formRow($form->get('name'));
// 	echo $this->formRow($form->get('email'));
// 	echo $this->formRow($form->get('access_level'));
// 	echo '<h3>Endre passord</h3>';
// 	echo $this->formRow($form->get('old_password'));
// 	echo $this->formRow($form->get('new_password'));
// 	echo $this->formRow($form->get('new_password_confirm'));
	
// 	echo $this->formRow($form->get('submit'));
	echo $this->form()->closeTag();
	?>
</div>