<?php
/**
 * @var \Acl\Form\EditUserForm|\Acl\Form\EditSoapUserForm $form
 */



$title = $this->translate('User');
$this->headTitle($title);

$this->getHelperPluginManager()->setAlias('formRow', \Iaasen\View\Helper\FormRowHorizontal::class);
$this->formCollection()->setDefaultElementHelper('formRowHorizontal');
$form->setAttribute('class', 'form-horizontal');
$form->prepare();

?>


<?php $this->placeholder('sidebar_left')->captureStart() ?>
<?php $this->placeholder('sidebar_left')->captureEnd() ?>

<?php $this->placeholder('sidebar_right')->captureStart() ?>
<?php $this->placeholder('sidebar_right')->captureEnd() ?>


<h1><?=$this->escapeHtml($title)?></h1>

<div class="form">
	<?php
        echo $this->form()->openTag($form);
        echo $this->formCollection($form);
        echo $this->form()->closeTag();
	?>
</div>