<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Acl\Module'                           => __DIR__ . '/Module.php',
    'Acl\Controller\AuthController'        => __DIR__ . '/src/Acl/Controller/AuthController.php',
    'Acl\Controller\UserController'        => __DIR__ . '/src/Acl/Controller/UserController.php',
    'Acl\Form\CreateUserForm'              => __DIR__ . '/src/Acl/Form/CreateUserForm.php',
    'Acl\Form\EditSoapUserForm'            => __DIR__ . '/src/Acl/Form/EditSoapUserForm.php',
    'Acl\Form\EditTokenForm'               => __DIR__ . '/src/Acl/Form/EditTokenForm.php',
    'Acl\Form\EditUserForm'                => __DIR__ . '/src/Acl/Form/EditUserForm.php',
    'Acl\Form\LoginForm'                   => __DIR__ . '/src/Acl/Form/LoginForm.php',
    'Acl\Model\AclStorage'                 => __DIR__ . '/src/Acl/Model/AclStorage.php',
    'Acl\Model\AuthElfagAdapter'           => __DIR__ . '/src/Acl/Model/AuthElfagAdapter.php',
    'Acl\Model\AuthLocalAdapter'           => __DIR__ . '/src/Acl/Model/AuthLocalAdapter.php',
    'Acl\Model\AuthService'                => __DIR__ . '/src/Acl/Model/AuthService.php',
    'Acl\Model\AuthSoapAdapter'            => __DIR__ . '/src/Acl/Model/AuthSoapAdapter.php',
    'Acl\Model\User'                       => __DIR__ . '/src/Acl/Model/User.php',
    'Acl\Model\UserTable'                  => __DIR__ . '/src/Acl/Model/UserTable.php',
    'Acl\Model\DbTable'                    => __DIR__ . '/src/Acl/Model/DbTable.php',
    'Acl\Model\Group'                      => __DIR__ . '/src/Acl/Model/Group.php',
    'Acl\Model\GroupTable'                 => __DIR__ . '/src/Acl/Model/GroupTable.php',
    'Acl\View\Helper\GroupselectionWidget' => __DIR__ . '/src/Acl/View/Helper/GroupselectionWidget.php',
);
