<?php
/**
 * @var Acl\Form\LoginForm $form
 * @var array $messages
 */
?>

<?php $this->placeholder('sidebar_left')->captureStart() ?>
<?php $this->placeholder('sidebar_left')->captureEnd() ?>

<?php $this->placeholder('sidebar_right')->captureStart() ?>
<?php $this->placeholder('sidebar_right')->captureEnd() ?>


<h1>Prosjektkalkulator er lagt ned</h1>



<div class="well">
    <p>Prøv vår nye Boligkalkulator v2:</p>

    <p><a href="https://boligkalkulator.elfag.no">https://boligkalkulator.elfag.no</a></p>

    <p>Boligkalkulator v2 er like enkel å bruke som Boligkalkulator samtidig som mulighetene til Prosjektkalkulator er videreført og forbedret.</p>
    <p>
        Prosjektkalkulator ble lagt ned 1. mars 2019.<br>
        Alle tilbud du har laget er tilgjengelig for utskrift og visning i den nye versjonen.
    </p>
</div>



<style>
    a:hover {
        font-weight: bold;
    }
</style>